import './globals.css'

import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light scroll-smooth"  dir="ltr">
      <body className={`bg-[#ECEFF2] dark:bg-gray-900 ${inter.className}`} >
      <Header/>

      {children}
      <Footer/>
      </body>
    </html>
  )
}
